apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: lazaruswebsite
build:
  artifacts:
  - image: lazarusnetwork/website
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yml
    - k8s/ingress.yml
